INSERT INTO archives (title, author, pages, characters, image, summary)

VALUES ('Dawn of the Jedi: Into the Void', 'Tim Lebbon', 320, 'Lanoree Brock, Dalien Brock, Tre Sana, Lorus', 'src\assets\SB-DawnOTJedi.png', 'On the planet Tython, the ancient Je"daii order was founded. And at the feet of its wise Masters, Lanoree Brock learned the mysteries and methods of the Force - and found her calling as one of its most powerful disciples. But as strongly as the Force flowed within Lanoree and her parents, it remained absent in her brother, who grew to despise and shun the Je"daii, and whose training in its ancient ways ended in tragedy.

Now, from her solitary life as a Ranger keeping order across the galaxy, Lanoree has been summoned by the Je"daii Council on a matter of utmost urgency. The leader of a fanatical cult, obsessed with traveling beyond the reaches of known space, is bent on opening a cosmic gateway using dreaded dark matter as the key - risking a cataclysmic reaction that will consume the entire star system. But more shocking to Lanoree than even the prospect of total galactic annihilation, is the decision of her Je"daii Masters to task her with the mission of preventing it. Until a staggering revelation makes clear why she was chosen: The brilliant, dangerous madman she must track down and stop at any cost is the brother whose death she has long grieved - and whose life she must now fear.' ),

('Darth Plagueis', 'James Luceno', 379, 'Darth Plagueis, Sheev Palpatine, Darth Maul, Padme Amidala, Obi-Wan Kenobi, Qui-Gon Jinn', 'src\assets\SB-DarthPlagueis.png', 'Darth Plagueis: one of the most brilliant Sith Lords who ever lived. Possessing power is all he desires. Losing it is the only thing he fears. As an apprentice, he embraces the ruthless ways of the Sith. And when the time is right, he destroys his Master—but vows never to suffer the same fate. For like no other disciple of the dark side, Darth Plagueis learns to command the ultimate power... over life and death.
 
Darth Sidious: Plagueis’s chosen apprentice. Under the guidance of his Master, he secretly studies the ways of the Sith, while publicly rising to power in the galactic government, first as Senator, then as Chancellor, and eventually as Emperor.
 
Darth Plagueis and Darth Sidious, Master and acolyte, target the galaxy for domination — and the Jedi Order for annihilation. But can they defy the merciless Sith tradition? Or will the desire of one to rule supreme, and the dream of the other to live forever, sow the seeds of their destruction?'),

('Maul: Lockdown', 'Joe Schreiber', 368, 'Darth Maul, Darth Sidious, Darth Plagueis, Artagan Truax, Iram Radique, Sadiki Blirr, Vesto Slipher', 'src\assets\SB-MaulLockDown.png', 'It"s kill or be killed in the space penitentiary that houses the galaxy’s worst criminals, where convicts face off in gladiatorial combat while an underworld gambling empire reaps the profits of the illicit blood sport. But the newest contender in this savage arena, as demonic to behold as he is deadly to challenge, is fighting for more than just survival. His do-or-die mission, for the dark masters he serves, is to capture the ultimate weapon: an object that will enable the Sith to conquer the galaxy.
 
Sith lords Darth Plagueis and Darth Sidious are determined to possess the prize. And one of the power-hungry duo has his own treacherous plans for it. But first, their fearsome apprentice must take on a bloodthirsty prison warden, a cannibal gang, cutthroat crime lord Jabba the Hutt, and an unspeakable alien horror. No one else could brave such a gauntlet of death and live. But no one else is the dreaded dark-side disciple known as Darth Maul.'),

('The Old Republic: Revan', 'Drew Karpyshyn', 298, 'Revan, Bastila Shan, Canderous Ordo, Lord Scourge, Darth Nyriss, Darth Xedrix', 'src\assets\SB-Revan.png', 'Revan: hero, traitor, conqueror, villain, savior. A Jedi who left Coruscant to defeat Mandalorians—and returned a disciple of the dark side, bent on destroying the Republic. The Jedi Council gave Revan his life back, but the price of redemption was high. His memories have been erased. All that’s left are nightmares—and deep, abiding fear.

What exactly happened beyond the Outer Rim? Revan can’t quite remember, yet can’t entirely forget. Somehow he stumbled across a terrible secret that threatens the very existence of the Republic. With no idea what it is, or how to stop it, Revan may very well fail, for he’s never faced a more powerful and diabolic enemy. But only death can stop him from trying.' ),

('The Old Republic: Deceived', 'Paul S. Kemp', 285, 'Lord Malgus, Lord Adraas, Ven Zallow, Vrath Xizor, Aryn Leneer', 'src\assets\SB-Deceived.png', 'A Sith warrior to rival the most sinister of the Order’s Dark Lords, Darth Malgus brought down the Jedi Temple on Coruscant in a brutal assault that shocked the galaxy. But if war crowned him the darkest of Sith heroes, peace will transform him into something far more heinous — something Malgus would never want to be but cannot stop becoming, any more than he can stop the rogue Jedi fast approaching. Her name is Aryn Leneer — and the lone Jedi Knight that Malgus cut down in the fierce battle for the Jedi Temple was her Master. Now she’s going to find out what happened to him, even if it means breaking every rule in the book.'),

('Red Harvest', 'Joe Schreiber', 256, 'Darth Scabrous, Tulkh, Dranok, Rojo Trace, Rance Lussk, Hartwig', 'src\assets\SB-RedHarvest.png', 'Unlike other young Jedi sidelined to the Agricultural Corps — those whose abilities have not proved up to snuff — Hestizo Trace possesses one extraordinary Force talent: a gift with plants. But suddenly her quiet existence among greenhouse and garden specimens is violently destroyed by the arrival of an emissary from Darth Scabrous, a Sith Lord with a fanatical dream poised to become nightmarish reality. For the rare black orchid that Hestizo has nurtured and bonded with is the final ingredient in an ancient Sith formula—crucial to the Dark Lord’s obsession, but with consequences far worse than fatal. Now, spawned by a heretofore unknown virus, the rotting, ravenous dead are rising, driven by a bloodthirsty hunger for all things living—and commanded by a Sith Master who lusts for power and the ultimate prize: immortality... no matter the cost.'),

('The Old Republic: Fatal Alliance', 'Sean Williams', 429, 'Dao Stryver, Darth Chratis, Eldon Ax, Jet Nebula, Satele Shan, Shigar Konshi', 'src\assets\SB-FatalAlliance.png', 'From across the galaxy they’ve come: agents of both the Republic and the Sith Empire, an investigating Jedi Padawan, an ex-trooper drummed out of the Republic’s elite Blackstar Squad, and a mysterious Mandalorian. An extraordinary auction has drawn them all together — in quest of a prize only one can claim. Each is prepared to do what he must to possess the treasure, whose value may be the wealth of a world itself. None intend to leave empty-handed. All have secrets, desires, and schemes. And nothing could ever unite them as allies — except the truth about the deadly danger of the object they covet. But can Sith and Jedi, Republic and Empire — enemies for millennia — join as one against the certain doom of the galaxy?'),

('The Old Republic: Annihilation', 'Drew Karpyshyn', 336, 'Marcus Trant, Theron Shan, Darth Karrid, Darth Marr, Jace Malcom', 'src\assets\SB-Annihilation.png', 'The Sith Empire is in flux. The Emperor is missing, presumed dead, and an ambitious Sith lord’s attempt to seize the throne has ended fatally. Still, Darth Karrid, commander of the fearsome Imperial battle cruiser Ascendant Spear, continues her relentless efforts to achieve total Sith domination of the galaxy.

But Karrid’s ruthless determination is more than matched in the steely resolve of Theron Shan, whose unfinished business with the Empire could change the course of the war for good. Though the son of a Jedi master, Theron does not wield the Force — but like his renowned mother, the spirit of rebellion is in his blood. As a top covert agent for the Republic, he struck a crucial blow against the Empire by exposing and destroying a Sith superweapon arsenal — which makes him the ideal operative for a daring and dangerous mission to end Ascendant Spear’s reign of terror.

Joined by hot-headed smuggler Teff’ith, with whom he has an inexplicable bond, and wise Jedi warrior Gnost-Dural, Darth Karrid’s former master, Theron must match wits and weapons with a battle-tested crew of the most cold-blooded dark side disciples. But time is brutally short. And if they don’t seize their one chance to succeed, they will surely have countless opportunities to die.');